USE [master]
GO
/****** Object:  Database [assignment2DB]    Script Date: 6/15/2022 10:28:38 PM ******/
CREATE DATABASE [assignment2DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'assignment2DB', FILENAME = N'D:\SQL\MSSQL15.SQLEXPRESS\MSSQL\DATA\assignment2DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'assignment2DB_log', FILENAME = N'D:\SQL\MSSQL15.SQLEXPRESS\MSSQL\DATA\assignment2DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [assignment2DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [assignment2DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [assignment2DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [assignment2DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [assignment2DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [assignment2DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [assignment2DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [assignment2DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [assignment2DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [assignment2DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [assignment2DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [assignment2DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [assignment2DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [assignment2DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [assignment2DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [assignment2DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [assignment2DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [assignment2DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [assignment2DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [assignment2DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [assignment2DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [assignment2DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [assignment2DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [assignment2DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [assignment2DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [assignment2DB] SET  MULTI_USER 
GO
ALTER DATABASE [assignment2DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [assignment2DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [assignment2DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [assignment2DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [assignment2DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [assignment2DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [assignment2DB] SET QUERY_STORE = OFF
GO
USE [assignment2DB]
GO
/****** Object:  Table [dbo].[Member]    Script Date: 6/15/2022 10:28:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Member](
	[MemberID] [int] NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[CompanyName] [varchar](40) NOT NULL,
	[City] [varchar](15) NOT NULL,
	[Country] [varchar](15) NOT NULL,
	[Password] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Member] PRIMARY KEY CLUSTERED 
(
	[MemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 6/15/2022 10:28:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[OrderID] [int] NOT NULL,
	[MemberID] [int] NOT NULL,
	[OrderDate] [datetime] NOT NULL,
	[RequiredDate] [datetime] NULL,
	[ShippedDate] [datetime] NULL,
	[Freight] [money] NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetail]    Script Date: 6/15/2022 10:28:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetail](
	[OrderID] [int] NOT NULL,
	[ProductID] [int] NOT NULL,
	[UnitPrice] [money] NOT NULL,
	[Quantity] [int] NOT NULL,
	[Discount] [float] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 6/15/2022 10:28:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[ProductID] [int] NOT NULL,
	[CategoryID] [int] NOT NULL,
	[ProductName] [varchar](40) NOT NULL,
	[Weight] [varchar](20) NOT NULL,
	[UnitPrice] [money] NOT NULL,
	[UnitInStock] [int] NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Member] FOREIGN KEY([MemberID])
REFERENCES [dbo].[Member] ([MemberID])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Member]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetail_Order] FOREIGN KEY([OrderID])
REFERENCES [dbo].[Order] ([OrderID])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderDetail_Order]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetail_Product] FOREIGN KEY([ProductID])
REFERENCES [dbo].[Product] ([ProductID])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderDetail_Product]
GO
USE [master]
GO
ALTER DATABASE [assignment2DB] SET  READ_WRITE 
GO
